FROM node:20-bookworm-slim

# Install Python and MkDocs dependencies
RUN apt-get update && apt-get install -y python3 python3-pip python3-venv curl && \
    rm -rf /var/lib/apt/lists/*

# install yq for YAML processing
RUN mkdir -p /usr/local/bin && \
    curl -sSL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_arm64 > /usr/local/bin/yq && chmod +x /usr/local/bin/yq

# Set up virtualenv for MkDocs
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
RUN pip install --upgrade pip
RUN pip install mkdocs-techdocs-core==1.3.1 mkdocs-kroki-plugin

# Install TechDocs CLI
RUN npm install -g @techdocs/cli

WORKDIR /src
ENTRYPOINT ["/bin/sh", "-c"]
